#################### USERS ####################
### CREATE USER
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Achmad Fahmi Al Hafidz",
  "email": "fahmialhafidza6@gmail.com",
  "password": "fahmi12345",
  "profile": {
    "identifyType": "KTP",
    "identifyNumber": "1234567890",
    "address": "Sidoarjo"
  }
}

### GET ALL USER
GET http://localhost:3000/api/v1/users

### GET DETAIL USER
GET http://localhost:3000/api/v1/users/1

#################### ACCOUNTS ####################
### CREATE ACCOOUNT
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
  "userId": "6",
  "bankName": "Bank BTN",
  "bankAccountNumber": "123456789",
  "balance": 350000.00
}

### GET ALL ACCOUNT
GET http://localhost:3000/api/v1/accounts

### GET DETAIL ACCOUNT
GET http://localhost:3000/api/v1/accounts/1

#################### TRANSACTION ####################
### CREATE TRANSACTION
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
  "sourceAccountId": 3,
  "destinasiAccountId": 4,
  "amount": 1000.00 
}

### GET ALL TRANSACTION
GET http://localhost:3000/api/v1/transactions

### GET DETAIL TRANSACTION
GET http://localhost:3000/api/v1/transactions/1